language: java
sudo: false
install: true


addons:
    sonarcloud:
        organization: "jlor-github"
        token:
              secure: "BA/0UBmYvMKOGJskouWk2TFBxlVPSEo0a5KFr7XyGouaiVWsfVrJGv81H1QiRSs3LlP6XqGuIlBN8WkVryPEzR6p6FkbnXnX6OcWq1Zlb/muI+qPVzb/L8hiWcwBjS3hF2Se3bt38HeZ/9Mr6B1datGbo9VDVArV/E+N9YqczjQR2bgWejLu2hZkAfYPh1PxQeM8S5JtXJ9eKUVTyQwHNFOTbIJExiGFP3atvtDQDy8qiS8VAc04ljLbwgUjUonpLbNz052tDZdVPg9ZWcRXWhMXRKBPtIApeH7g5NpxABN+i6p46MvqoBCLQdt/ADgk0q927c9m0m4oPKcuRbn9QpFBsQnDoDZaGzYK1kVoJJMB8dckrZZWNPHaIY7hYZx2LYqWcSlcj8oYrTpI0ZeZn6Y+y2bLRYQrrVrxcQmtZyUDF6YIU8LTRqf9Dy8B6+YlJKqUwVd8epf2T7da/I07nvlP5zUZyCQrBrdd9V4lbaB83RS5uYyegkabFR+/21EfYPbOsVrWzVatdQpNDU7Xpg5hPIyD9DYv2EFZMWABRJ3v3cf3soWIPX/ATuFpvPf5RGXdCWr5OKbXqyg32FH+1/lv5F8+RjCXR5X0ICLeNu0wTVOK7zgB69Xu7qSuOvcDtutYfq5KPb0Yy4Y4sFLYFY9S3UsKyp3Euh8iqwYMgPE="

jdk:
  - oraclejdk8
  
script:
    - mvn clean install sonar:sonar

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
